### ISSUE TITLE
great work; line 36 , a sudo command to compliment listing..

### ISSUE THREAD

**Issue by loknjinu13** [kaoxiong/Week8#1]
line 36 I added sudo fdisk -l /dev/${DEV1} , in oder to prevent any permission denied statement, especially as you want the user to check the device's status.
Your proposals to me here;
Can you help me show how to create multiple folders with your interactive style, i love the method and was thinking of some more fun. thanks...

**Comment by paveldanek** [comment]
Nice script, good job! Careful with permissions, though. For example, on some installations, you may not be (as you weren’t on mine) able to cd deep into /dev/ without using sudo!

**Comment by kaoxiong** [comment]
Thank you for the suggestions I will be more caution of the sudo command. I will also be adding more comment to my script to better show how they work.
